[env]
GO_VERSION = "1.24.3"

[tools]
go = "1.24.3"

[tasks.build]
description = "Build the slakctl binary"
run = "go build -o ./bin/slakctl"

[tasks.test]
description = "Run all tests"
run = "go test ./..."

[tasks.test-verbose]
description = "Run all tests with verbose output"
run = "go test -v ./..."

[tasks.clean]
description = "Clean build artifacts"
run = "rm -f ./bin/slakctl"

[tasks.fmt]
description = "Format Go code"
run = "go fmt ./..."

[tasks.vet]
description = "Run go vet"
run = "go vet ./..."

[tasks.mod-tidy]
description = "Tidy Go modules"
run = "go mod tidy"

[tasks.lint]
description = "Run linter and formatter"
depends = ["fmt", "vet"]

[tasks.check]
description = "Run all checks (lint, test)"
depends = ["lint", "test"]

[tasks.install]
description = "Install slakctl to $GOPATH/bin"
run = "go install"

[tasks.dev]
description = "Development workflow: format, lint, test, build"
depends = ["fmt", "vet", "test", "build"]
